# Schema for the configuration files of the Media Import module.
media_import.settings:
  type: config_object
  label: 'Media Import settings'
  mapping:
    family:
      type: number
      label: 'family'
    tour:
      type: number
      label: 'tour'
